---
- name: Add repository
  apt_repository:
    repo: ppa:tomtomtom/woeusb
  become: true

- name: Install
  apt:
    name: woeusb
    state: present
  become: true


- name: Graphics
  apt:
    name: woeusb-frontend-wxgtk
    state: present
  become: true
  when: graphics == true
